### ISSUE TITLE
"Bad connection" seems not to be applied independently

### ISSUE THREAD

**Issue by sukiletxe** [antiboredom/zoom-escaper#4]
Steps:
1. Speak or have something played through the input.
2. Just in case this is expected, don't rely that the output be the speakers. Do this as well, but record with some audio editor too.
3. Turn on only "bad connection".

Expected: The audio should be choppy.
Actual: The audio is not choppy. It is choppy with any of the other after effects, including echo.

**Comment by MrinmoyHaloi** [comment]
Yes. It also happens for me. Please fix it

**Comment by ritheshnayak** [comment]
how do i make my own websit by using these codes?

**Comment by MrinmoyHaloi** [comment]
> how do i make my own websit by using these codes?

What do you mean by these codes ?

**Comment by ritheshnayak** [comment]
just tell me how can i make a website like this one by using the source code avaliable in github
