### ISSUE TITLE
mic not detected when download the source code (Solved)

### ISSUE THREAD

**Issue by aviv926** [antiboredom/zoom-escaper#5]
Hello, I downloaded the source file to my computer, I ran the `index.html` file, he uploaded the site but he is unable to load the devices on my computer even though the site has access.
I tried to open with Microsoft Edge but it still did not introduce my voice / microphone devices

show this image: 
![image](https://user-images.githubusercontent.com/51673860/114575576-faa91a80-9c82-11eb-82a6-6b5210550470.png)

**Comment by antiboredom** [comment]
Hi - unfortunately you can't run the site by opening up the index as a file. If you want to run it locally rather than through zoomescaper.com you need to set up a static web server on your computer.

**Comment by aviv926** [comment]
I succeeded Thanks!
Anyone who wants to know how I succeeded I leave a short guide:

Download [Visual Studio Code](https://visualstudio.microsoft.com/downloads/) 
And after the installation, right-click on the folder we extracted and open it with Visual Studio Code
![image](https://user-images.githubusercontent.com/51673860/114578291-6db39080-9c85-11eb-98ac-939997debd0d.png)


In the software you install the live srever plugin you can do it using a keyboard shortcut `(ctrl shift x)`

This is the ID of the plugin: `ritwickdey.liveserver`

Then in the Visual Studio Code software go to the `index.html` file and right click on an **empty space** and click on Run via live server


![image](https://user-images.githubusercontent.com/51673860/114578075-41980f80-9c85-11eb-9775-75668708b5aa.png)
